<CFSILENT>
	<CFIF thisTag.executionMode eq "start">
	<CFPARAM NAME="ATTRIBUTES.ChildName"  >
	<CFPARAM NAME="ATTRIBUTES.Plural"     >
	<CFPARAM NAME="ATTRIBUTES.Singular"   >
	<CFPARAM NAME="ATTRIBUTES.TableName"  >
	<CFPARAM NAME="ATTRIBUTES.PKField"    >
	<CFPARAM NAME="ATTRIBUTES.LinkField"  >
	
	
	<CFASSOCIATE BASETAG="CF_CHILDREN" DATACOLLECTION="CHILDREN">
	</CFIF>
</CFSILENT>