<LINK href="../styles.css" type=text/css rel=stylesheet>
<P align=justify><EM><FONT color=#ff6600><STRONG>MotorhomeExchange-Sell.com</STRONG></FONT></EM><STRONG> </STRONG>is a website devoted to&nbsp;international motorhome exchange. The company also provides a forum for members and non-members to rent, sell and buy vehicles amongst themselves. The site was established by Penny Silva, a New Zealander.&nbsp;&nbsp;Penny is&nbsp;the owner/operator of the company.</P>
<P align=justify>Penny and her husband Mike purchased their first motorhome on Market Road,&nbsp;Camden,&nbsp;London in 1990. Market Road is a famous place for buying and selling motorhomes. They owned their motorhome for 4 years and travelled extensively throughout Europe and North Africa. During their travels they met several Europeans on motorhome exchange holidays. Penny began to collect ideas for <EM><STRONG><FONT color=#ff6600>MotorhomeExchange-Sell.com.</FONT></STRONG></EM> </P>
<P align=justify>Penny and her family currently live in Christchurch, New Zealand. They have owned their present motorhome for three and a half years. They have travelled in their motorhome throughout the South Island of New Zealand with their 3 young children. Penny and Mike have successfully taken part in 3 home exchanges within New Zealand. Motorhome exchange is a similar concept. </P>
<P align=justify></P>
<P align=justify>Penny’s personal aim is to prove and enlarge on the concept of successful international private motorhome exchange and rental. She would like to see this concept extended with similar "live in vehicles" i.e. caravans and travel trailers. She also aims to provide a forum for members and non-members to rent, buy and sell amongst themselves.&nbsp;Her assistant will be "the latest in computer technology." She aims to provide outstanding personalised customer service to all members and visitors to the site.</P><B>
<P><FONT color=#0066cc size=3>We hope you enjoy your visit to this site.</FONT><BR><BR></P>
<P align=center><IMG src="http://www.MotorhomeExchange-Sell.com/Images/huskImages/pic11.jpg"></P>
<P>&nbsp;&nbsp;&nbsp;&nbsp;</P></B>
