<CFSILENT>
	
	<CFPARAM NAME="ATTRIBUTES.#CFG.PlTablePrimaryKey#">
	
	<CFIF NOT IsDefined("ATTRIBUTES.Do_#ATTRIBUTES.FuseAction#")>
	
		<CFMODULE TEMPLATE="#CFG.TopLevel#" FuseAction="#CFG.PlName#Default" ATTRIBUTECOLLECTION=#ATTRIBUTES# />
		<CFSET RC = StructAppend(ATTRIBUTES, CFMODULE.ATTRIBUTES.DEFAULTVALUES, "No")>
		
	</CFIF>
</CFSILENT>
