CREATE TABLE IF NOT EXISTS email_verification_codes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    purpose text NOT NULL DEFAULT 'sign_up',
    code_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    used_at timestamptz,
    UNIQUE (email, purpose)
);
