CREATE TABLE IF NOT EXISTS listing_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id integer NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  url text NOT NULL,
  public_id text NOT NULL UNIQUE,
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS listing_images_listing_sort_idx
  ON listing_images(listing_id, sort_order);