<LINK href="../styles.css" type=text/css rel=stylesheet>
<P>Please <STRONG><A href="mailto:admin@MotorhomeExchange-Sell.com" target=""><STRONG>e-mail us</STRONG></A></STRONG> <FONT color=#0066cc><STRONG>&gt;&gt;&gt; </STRONG></FONT>with your motorhome exchange/rent/sell/buy success stories. If your story is chosen, we will publish it here. <BR><BR><FONT color=#ff6600><EM><STRONG><FONT size=3>MotorhomeExchange-Sell.com</FONT></STRONG></EM></FONT><FONT color=#0066cc size=3><STRONG> offers 1-year free membership for any story published on this page</STRONG>. </FONT></P>
<P align=justify>We are interested in all motorhome exchange stories previous to the launch of this site. What is the history of motorhome exchange? It is possible that motorhome exchange has been operating for decades! Only your first names and the area that you live in will be used &nbsp;e.g. Ben, from New York.</P>
<P align=justify>&nbsp;</P>
<P align=justify><FONT face=Tahoma size=3><STRONG>Michael - from The Netherlands</STRONG></FONT></P>
<P align=justify><FONT face=Tahoma size=2><STRONG>Motorhome Exchange</STRONG></FONT></P>
<P align=justify><FONT face=Tahoma size=2><STRONG>The Netherlands with Nimbin, Australia.</STRONG></FONT></P>
<P align=justify><FONT face=Tahoma size=2><STRONG>April - June 2000</STRONG></FONT></P>
<DIV><FONT face=Arial>"We had 7 reactions and we have chosen a couple in Nimbin, NSW, because they offered a brand new campervan,1 year old and 27000 k on. We prefered an Australian couple, we also had 5 reactions of immigrated dutch people, because we love it to meet foreign people. In april 2000 we flew to Brisbane and at the airport we have meet John and Lindy for the first time. From the first moment we had a very nice contact with them and now we are frends.</FONT></DIV>
<DIV><FONT face=Arial>We have spend 3 days in their house. John has given us instructions for the motorhome and Lindy for shopping, and then we start our trip.</FONT></DIV>
<DIV><FONT face=Arial>We drived to Sidney, Canberra, Melbourne, Port Augusta, Ayers Rock, Alice Springs,&nbsp;Kakadu, Darwin, Townsville, Cairns en back to Brisbane and Nimbin. We drived 18000 km in about 10 weeks.</FONT></DIV>
<DIV><FONT face=Arial>At this moment John and Lindy are making their trip in Europe with our motorhome, they are in Hungary at this moment, and they going to Tsechie, Slowakya and Poland. They also visit Rusland by train and park the van in Waszaw. Till now everything is going very well.&nbsp; </FONT><FONT face=Arial>For NZ I have an exchange with a couple in Lichfield. We fly to NZ in januari and arrive at Auckland 22 january. We will stay in NZ till 7 april, the day we fly back.</FONT>"</DIV>
<DIV>&nbsp;</DIV>
<DIV>&nbsp;</DIV>
<P align=justify><STRONG><FONT face=Tahoma size=3>Nev and Bev&nbsp; -&nbsp;&nbsp;from Victoria,&nbsp; Australia</FONT></STRONG></P><FONT face=Tahoma size=3><FONT face=Helvetica size=4>
<P><STRONG>Home &amp; Camper/Caravan Exchange </STRONG></P>
<P><STRONG>Victoria, Australia with Kent, UK. </STRONG></P>
<P><STRONG>May – November 2000</STRONG></P></FONT>
<P><STRONG>"A&nbsp;small article advising that ‘Max’</STRONG> <STRONG>from the Gold Coast in Queensland had a list of ‘caravanners’ who would be willing to exchange homes and rigs with Australians for up to 6 months during the year 2000.</STRONG></P>
<P><STRONG>It transpired that ‘Max’ had purchased a car &amp; caravan in the UK during 1985/86 and then spent 2 years touring the UK and Europe.&nbsp; In September 1998, he placed a small enquiry for an exchange of car &amp; caravan &amp;/or house in the club magazine. His hopes were to receive perhaps one or two replies from people who would like to exchange during 2000. By October he had over 35 replies, and after arranging his exchange, wrote back to all seeking an indication as to whether they would be prepared to exchange elsewhere in Australia.</STRONG></P>
<P><STRONG>‘Max’ forwarded to us a list of 18 replies with a short description and contact details. Most owned a car &amp; caravan and only 4 with motorhomes or campervans which proved unsuitable for one reason or another. One of our criteria was reasonable proximity to London in order to be close to friends and also facilitate family history research at the Family Research Centre near Clerkenwell.</STRONG></P>
<P><STRONG>One venue in Kent about 60 miles from London, seemed a likely choice although their van was older but in good condition. After further prompting from ‘Max’ (his aim was to place ALL the UK people who replied) just before Christmas, I rang ‘David’ one evening. His reaction was extreme surprise as he had assumed that the possibility of exchange was all a lost cause. We then engaged in numerous telephone conversations, e-mails, letters and exchanges of photographs during early 1999. When our London friends were invited to visit Kent for a traditional Sunday roast dinner in April, it quickly became apparent that an exchange with us was an excellent idea for the Kent couple as they had distant relatives in Melbourne. This meeting and a similar one here with their relatives alleviated personal anxieties, built on trust already established, and progressed plans in earnest. </STRONG></P>
<P><STRONG>We had a wonderful holiday, camping by the sea and a caravanning trip to Yorkshire, including 3 days in York and visits to old family friends near Bingley. The memories of being part of village life in Kent, the gardens and gardening (including first hand experience of the rapid late spring &amp; early summer growth in the garden) plus repeat visits to historic houses, towns, and various shows and displays will stay with us for a long while. </STRONG></P>
<P><STRONG>A three week canal boat cruise of the Grand Union Canal, the Thames River, and the Oxford Canal with friends from Melbourne was extremely enjoyable, and the English countryside in the "season of mists and mellow fruitfulness" was a sight never to be forgotten. We keep in touch with a retired couple we met on the Grand Union Canal and hope to be able to see them again.</STRONG></P>
<P><STRONG>Several of our village friends remain in contact including one couple who visited their family in Melbourne last February. ‘David’ and his wife who last time visited every State &amp; Territory in Australia, will be visiting Melbourne again during November this year. </STRONG></P>
<P><STRONG>We keep our eyes and ears open with our passports current, and hope to have another successful&nbsp; exchange really soon."</STRONG></P>
<P align=justify><BR></FONT>&nbsp;</P>
<P align=center><IMG src="http://www.MotorhomeExchange-Sell.com/Images/huskImages/pic2.jpg"></P>
<P align=justify>&nbsp;</P>
