<CFPARAM NAME="ATTRIBUTES.Name" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Address1" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Address2" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Address3" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Country" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Phone" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Fax" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Email" DEFAULT="">
<CFPARAM NAME="ATTRIBUTES.Comments" DEFAULT="">

